package com.behadd.e_commerce;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.widget.ImageView;
import android.widget.RatingBar;
import android.widget.TextView;
import android.widget.Toast;

import com.bumptech.glide.Glide;

import java.util.ArrayList;

public class MovieDetailsActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_movie_details);

        getIntents();
    }

    private void getIntents(){
        if(getIntent().hasExtra("Movie_Name") &&getIntent().hasExtra("Movie_Poster")
                &&getIntent().hasExtra("Movie_Position")){

            String name_detail, poster_detail;
            name_detail=getIntent().getStringExtra("Movie_Name");
            poster_detail=getIntent().getStringExtra("Movie_Poster");

            int position_detail=getIntent().getIntExtra("Movie_Position",10);
            LayoutMeinLagao(position_detail,name_detail.toUpperCase(),  poster_detail);
        }
        else
        {
            Toast.makeText(this, "Intent se extra maal nahi aaya!", Toast.LENGTH_SHORT).show();
        }
        
        if(getIntent().hasExtra("Movie_Rating")){

            RatingBar result= findViewById(R.id.ratingBarResult);
            float StarCount= getIntent().getFloatExtra("Movie_Rating", 0.0f);
            Toast.makeText(this, "You gave rating of: "+StarCount, Toast.LENGTH_SHORT).show();
            result.setRating(StarCount);
        }
    }
    
    
    
    
    
    
    public void LayoutMeinLagao(int position, String name, String poster){
        ImageView poster_mov;
        TextView Title, Description;

        Title=findViewById(R.id.tvTitle);
//        Rating=findViewById(R.id.tvRating);
        Description=findViewById(R.id.tvDescription);
        Description.setMovementMethod(new ScrollingMovementMethod());
        Title.setText(name);
  //      Rating.setText(rating);

        poster_mov=findViewById(R.id.ivPoster);
        Glide.with(this)
                .asBitmap()
                .load(poster)
                .into(poster_mov);



        ArrayList<String> descriptionArray = new ArrayList<>();
        descriptionArray.add("Rajesh Bauji (Sanjay Mishra) is a man in his late 50s, living a dreary but eventful life in a small house in old Delhi with his extended family. The movie starts with Babuji narrating his dream where he sees himself flying like a bird free from all the worldly affairs. A random incident is going to change his life in a dramatic way, though he does not realise it at the moment. Bauji's daughter has been seeing a boy of ill repute. When that fact is revealed to the family, after much deliberation they decide to lock up the girl and go beat the willful boy.\n" +
                "\n" +
                "When they confront the boy, to Babuji he seems like a very nice person. This event radically changes his life — he decides that he will believe only what he can see, hence the title Ankhon Dekhi. After a while he refuses to worship god and treats prasad as just another sweet. He is working as a travel agent and refuses to book tickets to Amsterdam as he has never seen Amsterdam. To uphold his ideals, he quits his job. He resorts to a very idealistic mode and takes things to extreme levels to explore his theory. At first his neighbours consider him a lunatic old man, but over time they start admiring his logical reasoning and start following him.\n" +
                "\n" +
                "Once while intervening in a petty loan issue with a loan shark, he refuses to believe the bad reputation of the shark. He concludes that he is a good person, based on his observation. He forms a rapport with the loan shark and is recruited by him in his illegal gambling den. His followers join.\n" +
                "\n" +
                "He gives consent to his daughter's marriage to the boy she loves and almost sorts out the emotional issues with his estranged brother.\n" +
                "\n" +
                "Now free from all responsibility, he leads a life where there are almost no blind spots and a lot of clarity. He takes his wife for a vacation.\n" +
                "\n" +
                "While chatting he narrates to his wife that he feels very light, like a bird flying in free skies. His wife jokes about his experience, inadvertently challenging his own theory that he doesn't know how a bird actually flies. In the middle of the night he walks towards a cliff. Babuji narrates his dream (as in the beginning of the story). He has yet to experience flying. As the film ends, Bauji is seen flying down a cliff.");

        descriptionArray.add("Set in present-day Varanasi, Uttar Pradesh, India, the plot of Masaan follows two seemingly separate stories that converge eventually.\n" +
                "\n" +
                "The first of these tells the story of college student Devi Pathak (Richa Chadda). The film opens with her and her fellow student, Piyush Aggarwal, checking into a hotel room. They are interrupted during sex when policemen burst in, having been tipped off by hotel staff who suspected Devi and Piyush were indulging in “indecent behaviour”. Inspector Mishra (Bhagwan Tiwari) records the barely clad Devi on his mobile phone while Piyush locks himself in the bathroom and commits suicide by slitting his wrists. Devi and her father Vidyadhar (Sanjay Mishra) are subjected to blackmail by Inspector Mishra, who demands a hefty bribe of three lakhs to hush up the matter. In desperate need of money, Vidyadhar begins to indulge in a betting game, where people bet on small boys to dive and collect the maximum number of coins from the Ganges riverbed within a specified time. He lets people bet on Jhonta (Nikhil Sahni), an orphan, that works for him after Jhonta volunteers himself for the game. Meanwhile, Devi has to switch jobs due to the stigma associated with her having pre-marital sex. She eventually gets a government job in the railways in Varanasi, but news regarding her pre-marital sexual indulgence reaches there as well.\n" +
                "\n" +
                "The second narrative concerns Deepak Kumar (Vicky Kaushal), a Varanasi boy from the Dom community (low castes, forced to work in \"dirty\" jobs due to the caste system) whose family works in cremation ghats by burning funeral pyres. Deepak wants to transcend the restrictions of a casteist society. He studies civil engineering at a polytechnic college where he meets and falls in love with Shaalu Gupta (Shweta Tripathi), a high caste Hindu girl. They start meeting each other and during a trip to Allahabad on the banks of the Ganges, they share an intimate moment. Back in Varanasi, Deepak tells her about his caste and the work he does burning corpses. Shaalu remains firm and tells him that she will be with him even if her parents refuse. She asks him to focus on his placements and get a job, while she reaffirms her commitment to him.\n" +
                "\n" +
                "However, unfortunately, during a pilgrimage trip with her family, Shaalu dies in a ghastly bus accident. Her body with those of other victims ends up at the same cremation ground where Deepak's family works. Deepak is shattered on seeing her dead body and loses all purpose in his life. He retains her ring as a souvenir. Deepak is eventually able to overcome his grief and discards Shaalu's ring in the Ganges. He gains a placement as a civil engineer in Allahabad. Later that same ring is picked up by Jhonta who loses consciousness underwater while collecting coins. He regains consciousness in hospital and gives the ring to a remorseful Vidyadhar, who decides to stop playing with Jhonta's life. He sells the ring and is finally able to pay off Inspector Mishra.\n" +
                "\n" +
                "Marred by the parochial mindset of people regarding her situation, Devi leaves Varanasi and joins a course in Allahabad. She comes to the banks of the Ganges to immerse the gift Piyush had given to her on that fateful day in the hotel. Deepak, who was also sitting by the bank, notices her crying and offers her water to drink. A boatman beckons, offering both of them a ride towards Sangam. They both board the boat and strike up a conversation.");
        descriptionArray.add("Years after the Civil War, bounty hunter Major Marquis Warren is transporting three dead bounties to the town of Red Rock, Wyoming. He hitches a ride on a stagecoach driven by O.B. Jackson. Aboard is John Ruth, a bounty hunter known for bringing in outlaws alive to see them hang; handcuffed to him is fugitive Daisy Domergue, whom Ruth is escorting to Red Rock. Ruth is suspicious of anyone who might steal his claim to the bounty. Ruth and Warren bond over Warren's personal letter from Abraham Lincoln.\n" +
                "\n" +
                "Former Lost-Causer militiaman Chris Mannix, who claims he is traveling to Red Rock as the town's new sheriff, persuades Ruth and Warren to let him on the stagecoach. Warren and Ruth form an alliance to protect each other's bounties. Mannix and Warren almost come to blows over their controversial war records.\n" +
                "\n" +
                "The group seeks refuge from a blizzard at Minnie's Haberdashery, a stagecoach lodge. They are greeted by Bob, a Mexican, who says the owner, Minnie, is visiting her mother. The other lodgers are Oswaldo Mobray, a hangman; Joe Gage, a quiet cowboy traveling to visit his mother; and Sanford Smithers, a former Confederate general traveling to put his missing son to rest. Suspicious, Ruth disarms all but Warren. As the group eats, Mannix surmises that Warren's Lincoln letter is a forgery. Warren admits this, saying the letter buys him leeway with whites, outraging Ruth. Warren leaves a gun next to Smithers and provokes him into reaching for it by telling Smithers he tortured, raped, and killed Smithers' son. When Smithers pulls a gun, Warren shoots him as revenge for Smithers' execution of black soldiers at the Battle of Baton Rouge.\n" +
                "\n" +
                "While everyone is distracted by the confrontation, someone seen only by Daisy poisons the brewing coffee. Ruth and O.B. drink it, causing them to vomit blood, killing O.B. The dying Ruth attacks Daisy, but she kills him with his own gun. Warren disarms Daisy, holds the men at gunpoint and leaves her cuffed to Ruth's corpse. Warren is joined by Mannix, whom Warren trusts because he nearly drank the poisoned coffee. Warren executes Bob, deducing that he is an impostor who killed the lodge owners, as Minnie hates Mexicans and would never leave one to care for the lodge. When Warren threatens to execute Daisy, Gage admits that he poisoned the coffee. A man hiding in the cellar shoots Warren in the genitals. Mobray draws a concealed gun and shoots Mannix, who returns fire, wounding Mobray and forcing Gage against the wall.\n" +
                "\n" +
                "Hours earlier, Bob, Mobray, Gage, and a fourth man, Jody, arrive at Minnie's Haberdashery. They murder Minnie and five other bystanders, leaving only Smithers. Jody, Daisy's brother, tells Smithers they plan to ambush Ruth to rescue Daisy; his gang will spare Smithers if he keeps quiet, as they deduce that an extra lodger makes the setup more believable. The bandits dispose of the bodies, hide the evidence, and conceal guns around the lodge. As Ruth's stagecoach arrives, Jody hides in the cellar.\n" +
                "\n" +
                "In the present, Mannix and Warren, both seriously wounded, hold Daisy, Gage, and the dying Mobray at gunpoint. They force Jody out of the cellar by threatening to kill Daisy. Jody surrenders and Warren executes him. Daisy claims fifteen of her brother's men are waiting in Red Rock to kill Mannix and ransack the town; if Mannix kills Warren and allows her to escape, the gang will spare him and let him claim the bounties of the deceased except her brother.\n" +
                "\n" +
                "As Daisy and Mobray taunt Warren, Warren shoots Daisy in the foot and Mobray in the leg; Mobray soon dies from his wounds. Gage draws a hidden revolver but is shot dead by Mannix and Warren. Warren tries to shoot Daisy but is out of bullets. Mannix calls Daisy's bluff and rejects her offer, but faints from blood loss. Daisy hacks off Ruth's handcuffed arm and frees herself. As she reaches for a gun, Mannix regains consciousness, shoots, and wounds her. Warren persuades Mannix to hang her from the rafters in honor of Ruth. Afterward, as the two men lie dying, Mannix reads aloud Warren's forged Lincoln letter.");
        descriptionArray.add("In late 1975, the heavyweight boxing world champion, Apollo Creed, announces plans to hold a title bout in Philadelphia during the upcoming United States Bicentennial. However, he is informed five weeks from the fight date that his scheduled opponent is unable to compete due to an injured hand. With all other potential replacements booked up or otherwise unavailable, Creed decides to spice things up by giving a local contender a chance to challenge him. He settles in on Rocky Balboa, an aspiring southpaw boxer from an Italian neighborhood of Philadelphia, known by the nickname \"The Italian Stallion\".\n" +
                "\n" +
                "Rocky meets with promoter Miles Jergens, unexpectedly presuming Creed is seeking local sparring partners. Reluctant at first, Rocky eventually agrees to the fight which will pay him $150,000. After several weeks of training, using whatever he can find, including meat carcasses as punching bags, Rocky accepts an offer of assistance from former boxer Mickey \"Mighty Mick\" Goldmill, a respected trainer and former bantamweight fighter from the 1920s, who always criticized Rocky for wasting his potential.\n" +
                "\n" +
                "Meanwhile, Rocky meets Adrian Pennino, who is working part-time at the J&M Tropical Fish pet store. He begins to build a romantic relationship with Adrian, culminating in a kiss. Adrian's brother, Paulie, becomes jealous of Rocky's success, but Rocky calms him by agreeing to advertise his meatpacking business before the upcoming fight. The night before the fight, Rocky begins to lose confidence after touring the arena. He confesses to Adrian that he does not expect to win, but is content to go the distance against Creed and prove himself to everyone.\n" +
                "\n" +
                "On New Year's Day, the fight is held, with Creed making a dramatic entrance dressed as George Washington and then Uncle Sam. Taking advantage of his overconfidence, Rocky knocks him down in the first round—the first time that Creed has ever been knocked down. Humiliated, Creed takes Rocky more seriously for the rest of the fight, though his ego never fully fades. The fight goes on for the full fifteen rounds, with both combatants sustaining various injuries. As the fight progresses, Creed's superior skill is countered by Rocky's apparently unlimited ability to absorb punches, and his dogged refusal to go down. As the final round bell sounds, with both fighters locked in each other's arms, they promise to each other that there will be no rematch.\n" +
                "\n" +
                "After the fight, the sportscasters and the audience go wild. Jergens announces over the loudspeaker that the fight was \"the greatest exhibition of guts and stamina in the history of the ring\", and Rocky calls out repeatedly for Adrian, who runs down and comes into the ring as Paulie distracts arena security. As Jergens declares Creed the winner by virtue of a split decision (8:7, 7:8, 9:6), Adrian and Rocky embrace and profess their love to each other, not caring about the result of the fight.");
        descriptionArray.add("The movie starts with Raju (Dev Anand) being released from jail. Raju was a freelance guide, who earned his living by taking tourists to historic sites. One day, a wealthy and aging archaeologist, Marco (Kishore Sahu) comes to the city with his young wife Rosie (Waheeda Rehman), the daughter of a courtesan. Marco wants to do some research on the caves outside the city and hires Raju as his guide.\n" +
                "\n" +
                "While Marco devotes himself to the discovery of the cave, Raju takes Rosie on a tour and appreciates her dancing ability and innocence. He learns about Rosie's background as a daughter of a virgin courtesan and how Rosie has achieved respectability as the wife of Marco but at a terrible cost. She had to give up her passion of dancing since it was unacceptable to Marco. Meanwhile, Rosie tries to commit suicide by consuming poison. Marco, upon learning of the incident, returns from the caves to see Rosie and is furious with Rosie after seeing her alive. He tells her that her act of committing suicide was a drama, otherwise she would have consumed more sleeping pills so that she could really have died. Upon returning to the caves which were discovered, Rosie learns that Marco is spending time and enjoying the company of a native tribal girl. She is enraged at Marco and both indulge in a serious heated discussion, which concludes with Rosie leaving the caves, and she once again wants to end her life.\n" +
                "\n" +
                "Raju calms her down by saying that committing suicide is a sin, and that she should live to pursue her dream. She finally says good-bye to the relation of being the wife of Marco. Now she needs support and a home. Raju gives her shelter. Rosie is considered a prostitute by Raju's community (as classical dancing traditionally was prostitutes' work at royal courts), which leads to many problems, including his mother and her brother insisting that Rosie be kicked out. Raju refuses and his mother leaves him. His friend and driver also falls out with him over Rosie. Raju loses his business and the entire town turns against him. Undeterred by these setbacks, Raju helps Rosie embark on a singing and dancing career and Rosie becomes a star. As she rises as a star, Raju becomes dissolute — gambling and drinking. Marco comes back on the scene. Trying to win Rosie back, he brings flowers and has his agent ask Rosie to release some jewelry which is in a safe deposit box. Raju, a bit jealous, does not want Marco to have any contact with Rosie and forges Rosie's name on the release of the jewels. Meanwhile, Rosie and Raju drift apart due to Rosie's incomprehensible behaviour when she tortures Raju by not obliging him a caring hug even and asks him to leave her room else she says she will have to go out. Before this, they also had a discussion about how a man should live when Rosie remembers Marco and tells Raju that Marco was probably correct when he used to say that a man should not live on a woman's earnings.\n" +
                "\n" +
                "Raju retorts by saying that she is under a misunderstanding that she has become a star on her own and it was only because of Raju's efforts that she became famous. Later, Rosie learns of the forgery release. Raju is convicted of forgery, resulting in a two-year sentence. Rosie does not understand why Raju indulged in forgery, when he could have easily asked her for money. It was not money, it was the loving fascination for Rosie which urged Raju not to reveal Marco's visit to Rosie so that she doesn't remember him again and to eliminate the probability of Rosie and Marco's togetherness, if at all, there was any little chance. On the day of his release, his mother and Rosie come to pick him up but they are told that he was released six months ago because of his good behaviour.\n" +
                "\n" +
                "Meanwhile, upon his release Raju wanders alone. Despair, poverty, rags, hunger, and loneliness engulf him until he finds a wandering group of sadhus (holy men) with whom he spends a night at a derelict temple in a small town.Raju impresses the woman with the logic in taking a husband and she submits, which convinces Bhola that Raju is a swami (holy man). Impressed by this, Bhola spreads the news through the village. Raju is taken as a holy man by the village. Raju assumes the role of village holy man (Swami Ji) and engages in skirmishes with the local pandits.And drama started here. Due to drought Raju was forced to fast for 12 days so that it rains. Meanwhile, his mother, friend and Rosie unite with him and patch things up. In the end it rains but Raju dies.");
        descriptionArray.add("Dan Millman is a university student as well as a locally famous gymnast who dreams of winning a National Championship competition. He suffers from restlessness, and on one occasion, Dan attempts to compensate for the restlessness by running along streets before sunrise. At a car-service station, he encounters an old man who seems to know more about Dan's problem than Dan himself knows, whom Dan later nicknames \"Socrates\". Dan is unsettled by Socrates' knowledge; by the fact that Socrates had appeared in a nightmare as a faceless janitor, clad in mismatched shoes (by which he is identified in waking life), who sweeps up the pieces of Dan's shattered leg; and by the old man's extraordinary speed, agility, and coordination. As a result of his exposure to the last, Dan seeks to learn the secret behind it.\n" +
                "\n" +
                "Socrates, prodded by the impatient and defiant Dan, gives the boy a series of tasks and lessons. The central concept of \"Soc's\" philosophy is this: that one must live entirely in the present moment. Other ideas include the related notion that at no time is \"nothing going on\" and the idea that an appropriate time exists for fighting and another for abstaining from violence. These lessons are conveyed through practical lessons, long contemplation, and one spectacular mystical experience. Dan gradually learns to appreciate every moment; to view the journey toward a goal as more meaningful and significant than the attainment; to pay attention to that which he is doing – thus increasing his gymnastic prowess; and (to a slightly lesser extent) control himself. Throughout the lesson, Dan learns virtually nothing about his mentor, other than the philosophy, Socrates' belief that service is the most noble action possible (hence his choice to work as a car serviceman), and the presence of another protégé.\n" +
                "\n" +
                "This protégé, a woman of Dan's own age named Joy, has learned and integrated Socrates' philosophy into her life, to the extent that she seems as wise as Socrates himself. Dan attempts to ask her for information regarding Socrates, but receives little. Joy treats Dan indulgently, though she evidently respects him.\n" +
                "\n" +
                "One day, Dan drives recklessly, and his motorcycle collides with a car that ran a red light, causing his right femur bone to shatter. He is rushed to a hospital, where a metal bar is placed in his leg to maintain its integrity. As a result, his gymnastic coach believes that Dan cannot compete in the National competition. Dan, hurt by this lack of faith, recovers from the injury and resumes his training under Socrates' tutelage. Eventually, he is restored to full health and strength, while his coordination improves and his mind is set entirely on the present moment. He competes in the U.S. Trials for the Olympics and achieves a victory.\n" +
                "\n" +
                "Slightly before the competition, Dan diverts the bus he is riding to Socrates' station, only to find that Socrates has vanished without a trace. At the arena, he attempts to teach his teammate Tommy what he has learned, but fails due to Tommy's emotional insecurity and lack of comprehension. Dan then is called upon for his turn to perform on the still rings. While he does his routine, Dan performs flawlessly just like Pommel Horse tryouts. Moments before he completes his routine, Socrates is in his thoughts asking him three questions: \"Where are you, Dan?\" \"Here.\" \"What time is it?\" \"Now.\" \"What are You?\" \"This Moment.\" Dan then performs his triple consecutive flips, the Commentators frantically speaking, and the judges staring at him in amazement. He then dismounts, while the rings swing outwards, eventually touching each other. The screen goes black, leaving his last moment unknown.\n" +
                "\n" +
                "The postscript states that Dan and his Berkeley Gymnastics Team won their first National title. It is implied at the end, in a postscript appearing on screen, that Dan of the film and Dan the author of the book on which the film is based are one and the same. It is also stated that the latter Dan lives with his wife Joy.");
        descriptionArray.add("In 1981, San Francisco salesman Chris Gardner invests his entire life savings in portable bone density scanners, which he demonstrates to doctors and pitches as a handy quantum leap over standard X-rays. The scanners play a vital role in his life. While he is able to sell most of them, the time lag between the sales and his growing financial demands enrage his already bitter and alienated wife Linda, who works as a hotel maid. The financial instability increasingly erodes their marriage, in spite of them caring for Christopher Jr., their soon-to-be five-year-old son.\n" +
                "\n" +
                "While Chris is trying to sell one of the scanners, he meets Jay Twistle, a manager for Dean Witter Reynolds, and impresses him by solving a Rubik's Cube during a taxi ride. After Jay leaves, Gardner lacks money to pay the fare and chooses to run instead, causing the driver to angrily chase him into a BART station. Gardner boards a train but loses one of his scanners in the process. His new relationship with Jay earns him the chance to become an intern stockbroker. The day before the interview, Gardner grudgingly agrees to paint his apartment so as to postpone being evicted due to his difficulty in paying the rent. While painting, Gardner is greeted by two policemen at his doorstep, who take him to the station, stating he has to pay for the numerous parking tickets he has accumulated. As part of the sanction, Gardner is ordered to spend the night in jail instead, complicating his schedule for the interview the next morning. He manages to arrive at Dean Witter's office on time, albeit still in his shabby clothes. Despite his appearance, he impresses the interviewers and lands an unpaid internship. He would be amongst 20 interns competing for a paid position as a stockbroker.\n" +
                "\n" +
                "Gardner's unpaid internship does not please Linda, who eventually leaves for New York City because she might get a job at her sister's boyfriend's new restaurant. After Gardner bluntly says she is incapable of being a single mom, she agrees that Christopher Jr. will remain with his dad. Gardner is further set back when his bank account is garnished by the IRS for unpaid income taxes, and he and Christopher are evicted. He ends up with less than $22, resulting in them being homeless, and they are forced at one point to stay in a restroom at a BART station. Other days, he and Christopher spend nights at a homeless shelter, in BART, or, if he manages to procure sufficient cash, at a hotel. Later, Gardner finds the bone scanner that he lost in the BART station earlier and, after repairing it, sells it to a physician, thus completing all his sales of his scanners.\n" +
                "\n" +
                "Disadvantaged by his limited work hours, and knowing that maximizing his client contacts and profits is the only way to earn the broker position, Gardner develops a number of ways to make phone sales calls more efficiently, including reaching out to potential high-value customers, defying protocol. One sympathetic prospect who is a top-level pension fund manager even takes Chris and Christopher to a San Francisco 49ers game. Regardless of his challenges, he never reveals his lowly circumstances to his colleagues, even going so far as to lend one of his bosses $5 for cab fare, a sum that he cannot afford. Concluding his internship, Gardner is called into a meeting with his managers. One of them notes he is wearing a shirt. Gardner explains it is his last day and thought to dress for the occasion. The manager smiles and says he should wear another one tomorrow, letting him know that he has won the coveted full-time position and giving him back his $5 as he promised. Fighting back tears, Gardner shakes hands with them, then rushes to his son's daycare to embrace Christopher. They walk down the street, joking with each other (and are passed by the real Chris Gardner, in a business suit). The epilogue reveals that Gardner went on to form his own multimillion-dollar brokerage firm.");
        descriptionArray.add("Nikhil (Sidharth Malhotra) is a struggling businessman, who thinks he loves Karishma (Adah Sharma), an actress. Nikhil is characterized as a person who believes that once you are committed to a girl, there should be no straying. Karishma asks Nikhil to arrange ₹50 million (US$750,000) before marriage, which is 7 days later, to earn a contract.\n" +
                "\n" +
                "Nikhil meets Meeta (Parineeti Chopra), Karishma's younger sister, with whom he had a brief encounter 7 years ago. Meeta, who is an IITian in Chemical Engineering and PhD., is a super-intelligent geek with unusual behaviour and habits, who ran away 7 years ago to China after stealing money from her own father, leading to his heart attack. Now, just a week before Nikhil and Karishma's wedding, Meeta has turned up to meet her father, but Karishma is scared that her sister's sudden appearance might ruin their wedding. Hence, Karishma assigns Nikhil to keep Meeta away from her father (Manoj Joshi).\n" +
                "\n" +
                "Meeta has returned with an intention to steal again but her involvement with Nikhil during the next 7 days diverts her attention. During these 7 days, with many personal and social activities, Nikhil and Meeta fall in love but Nikhil backs off as he doesn't want to betray Karishma. He comes to know that for her research, Meeta has taken a heavy loan of ₹100 million (US$1.5 million) from a Chinese investor by forging her father's signature. The deadline for payback is over and an extension of three days was given, during which she has to steal money from her father's account to save him from the investor's goons. Nikhil helps Meeta to hack her father's account but advises her to apologize to her family. Meeta reunites with her family and Nikhil realizes he is marrying the wrong girl.\n" +
                "\n" +
                "Meeta is unable to gather the courage to steal her father's money and tells her father the truth. Her father forgives her and provides her with the money. Nikhil later tells Meeta on the phone that he should have gone with her to Goa when she asked him to come with her 7 years ago. Meeta tells him that it is not too late for them to run away.\n" +
                "\n" +
                "When Nikhil comes to Meeta's house to run away with her, he sees Karishma with her family and returns home, realizing the complications. Nikhil later scolds Meeta for being so ready to run away and says that he cannot torture Karishma even though Karishma has emotionally tortured him throughout their relationship. Nikhil leaves Meeta and tells her to go away from here. Later that night Nikhil receives the call of his investor Mr. Adlani and gets the news that he liked his plan and is ready to invest in his plan.\n" +
                "\n" +
                "On the wedding day, Meeta leaves her house without informing anyone except her father, leaving her mobile phone inside Karishma's room. Nikhil tries to call her and sends many texts, which go unanswered. On reaching the mandap Meeta's father informed him that she has already left for china. Karishma finds Meeta's phone in her room, reads the messages, and realizes she has lost Nikhil. During the wedding she asks Nikhil to leave the wedding, her decision is supported by her father. Meeta on the airport cries hard and tries to end her life but gives up that decision and goes back to wedding. The two reunite and express their love.\n" +
                "\n" +
                "The movie ends with Nikhil and Meeta at the airport, scheduled to travel to Germany. Meeta tells him that there is another problem waiting for them.");
        descriptionArray.add("The film is divided into three parts from the view of the main characters:\n" +
                "Paro\n" +
                "\n" +
                "Paro (Mahi Gill) is an idealistic, young, lower-middle class girl living in Punjab. Her childhood sweetheart is Dev (Abhay Deol), the son of a rich businessman. Paro cares for him immensely, and fully expects a future with him. Dev constantly takes Paro's love and affection for granted. He grows up to be arrogant and lazy, which causes his father to send him to London to complete his education. While separated by distance, Paro and Dev's youthful love only blossoms more, despite Dev becoming increasingly more egotistical and entitled. After finishing his studies, Dev returns to Chandigarh and meets Paro, and they rekindle their romance. After some time, Dev overhears scandalous rumours about Paro concerning her reputation and sexual history, which he immediately believes. Paro is shocked to see Dev's chauvinist attitude towards her, even after she claims innocence. Dev hypocritically passes judgement on Paro and does not approve of the things that he has heard. Paro turns her back on him when she hears him insult her and rashly agrees to marry a man of her parents' choice. On her wedding day, Dev learns that the rumors were false but his ego doesn't let him accept his mistake, and he lets Paro marry someone else.\n" +
                "Chanda\n" +
                "\n" +
                "Leni (Kalki Koechlin) is a Delhi student of half-European descent. A date with her much older boyfriend turns sexual and lands Leni in an MMS sex scandal. The incident becomes public knowledge after the video is widely circulated. Her father, having watched the video, commits suicide out of shame and disgust, and Leni's family decides to send her to live in a small rural town. Refusing to live a life of shame and ridicule, she returns to Delhi where she works as a prostitute at night, while continuing with her studies during the day. She adopts the name 'Chanda' for her profession. Her 'foreign' looks mean her services are reserved for the highest-paying customers and she finds some dignity and independence in the new way of living. One night, an inebriated, half-conscious customer is brought to her room - it turns out to be Dev.\n" +
                "Dev\n" +
                "Dev, tormented by Paro’s wedding, has been seeking refuge in alcohol and drugs. He finds some solace with Chanda but is unable to forget Paro. While in a drug fueled haze, he calls Paro's husband in the middle of the night, Paro visits him at the cheap lodge where he is staying. She shows her love by taking care of him but spurns his attempts at physical intimacy. The meeting ends on a bitter note, and Paro returns to her married life. Dev resolves to go back to Chanda, but confronted by the reality of her profession, he abandons her, too. He resumes his destructive lifestyle of alcohol, drugs, and reckless behaviour. Months later, after his life has completely fallen apart and hit an all-time low, Dev attempts to pick up the pieces. He seeks Chanda once again and, with her help, sets out to start life afresh.");
        descriptionArray.add("Truman Burbank is the unsuspecting star of The Truman Show, a reality television program which is broadcast live around the clock and across the globe. His entire life has taken place within a giant arcological dome in Hollywood, fashioned to create the seaside town of Seahaven Island, and equipped with thousands of cameras to monitor all aspects of his life. The producers discouraged Truman from wanting to leave Seahaven by instilling him with aquaphobia through the \"death\" of his TV father in a boating \"accident\", and by constantly broadcasting and printing messages of the dangers of traveling. All of Seahaven's residents are actors, either acting out a script or repeating lines fed to them by the show's creator and executive producer, Christof. Christof seeks to capture Truman's real emotion and human behavior and give audiences a relatable everyman.\n" +
                "\n" +
                "Despite Christof's control, Truman manages to act in unexpected ways. During his college years, Truman was intended to fall in love with and marry co-student Meryl, but he fell in love with another actress, Sylvia. Sylvia managed to bring Truman out of the sight of cameras long enough to warn him that his reality is fake before she was taken away, with her \"father\" claiming they are traveling to Fiji. While Truman went on to marry Meryl, he continues to fantasize about Sylvia, using scraps from magazines to recreate her face in secret, and seeks travel to Fiji. Outside of the show, Sylvia has become part of a \"Free Truman\" campaign that demands the end of the show.\n" +
                "\n" +
                "The film begins during the thirtieth year of the show. Truman starts noticing unusual events that seem centered on him: a falling spotlight, rain that only falls on him, and a radio channel that precisely describes his movements. Truman spots a disheveled man and recognizes him as his father, who had snuck back into the set, but other actors quickly drag the man away. Despite efforts by Meryl and Truman's best friend Marlon to reassure him, Truman becomes even more suspicious about his life. One day, he takes Meryl by surprise by going on an impromptu road trip, but their way is blocked by increasingly implausible emergencies. Meryl begins to break down from the stress; during an argument with Truman, she breaks character and is taken off the show. Hoping to bring Truman back to a controllable state, Christof re-introduces Truman's father to the show properly, under the guise of having lost his memory after the boating accident.\n" +
                "\n" +
                "Truman seems to return to his routines, except that after Meryl moves out he begins sleeping in his basement. One evening the production staff discovers that the sleeping Truman is completely out of their sight. Marlon is sent to check on Truman, finding that he has left a dummy and a tape recorder in his place and disappeared through a makeshift tunnel. Marlon breaks character, and Christof orders the first transmission cut in the show's history while a citywide search for Truman is launched. Audiences around the world are drawn to this sudden change. Truman is found sailing out of Seahaven, having conquered his fear of water, and Christof resumes the broadcast as he sends a man-made lightning storm to try to capsize the boat. Network executives fear that Truman may die on live television, but Truman manages to persist. Realizing he cannot dissuade Truman any further, Christof ends the storm.\n" +
                "\n" +
                "Truman continues to sail until – to his surprise – his boat punctures the wall of the dome. He finds an exit door, but Christof, speaking directly to Truman through a speaker system, tries to convince him to stay, stating there is \"no more truth\" in the real world and that by staying in his artificial world, he would have nothing to fear. Truman considers this, then states: \"In case I don't see you... good afternoon, good evening, and good night,\" previously his unwitting catch-phrase, takes a bow, and leaves. Sylvia races to meet Truman, while Christof's supervisors end the show for the last time and the audience starts looking for something else to watch.");

        String daalo=descriptionArray.get(position);
        Description.setText(daalo);
    }
}
